package com.ProClinic.pojo;

public class DoctorInfo {
    @Override
    public String toString() {
        return "DoctorInfo{" +
                "doctorId=" + doctorId +
                ", doctorName='" + doctorName + '\'' +
                ", doctorSex='" + doctorSex + '\'' +
                ", doctorDepartment='" + doctorDepartment + '\'' +
                ", doctorStatus=" + doctorStatus +
                ", doctorWorkAge=" + doctorWorkAge +
                ", doctorAge=" + doctorAge +
                ", doctorPhone='" + doctorPhone + '\'' +
                ", doctorPhoto='" + doctorPhoto + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_name
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_sex
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String doctorSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_department
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String doctorDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_status
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer doctorStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_work_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer doctorWorkAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer doctorAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_phone
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String doctorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_info.doctor_photo
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String doctorPhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_id
     *
     * @return the value of doctor_info.doctor_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_id
     *
     * @param doctorId the value for doctor_info.doctor_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_name
     *
     * @return the value of doctor_info.doctor_name
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_name
     *
     * @param doctorName the value for doctor_info.doctor_name
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_sex
     *
     * @return the value of doctor_info.doctor_sex
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getDoctorSex() {
        return doctorSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_sex
     *
     * @param doctorSex the value for doctor_info.doctor_sex
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorSex(String doctorSex) {
        this.doctorSex = doctorSex == null ? null : doctorSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_department
     *
     * @return the value of doctor_info.doctor_department
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getDoctorDepartment() {
        return doctorDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_department
     *
     * @param doctorDepartment the value for doctor_info.doctor_department
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorDepartment(String doctorDepartment) {
        this.doctorDepartment = doctorDepartment == null ? null : doctorDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_status
     *
     * @return the value of doctor_info.doctor_status
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getDoctorStatus() {
        return doctorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_status
     *
     * @param doctorStatus the value for doctor_info.doctor_status
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorStatus(Integer doctorStatus) {
        this.doctorStatus = doctorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_work_age
     *
     * @return the value of doctor_info.doctor_work_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getDoctorWorkAge() {
        return doctorWorkAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_work_age
     *
     * @param doctorWorkAge the value for doctor_info.doctor_work_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorWorkAge(Integer doctorWorkAge) {
        this.doctorWorkAge = doctorWorkAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_age
     *
     * @return the value of doctor_info.doctor_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getDoctorAge() {
        return doctorAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_age
     *
     * @param doctorAge the value for doctor_info.doctor_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorAge(Integer doctorAge) {
        this.doctorAge = doctorAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_phone
     *
     * @return the value of doctor_info.doctor_phone
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getDoctorPhone() {
        return doctorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_phone
     *
     * @param doctorPhone the value for doctor_info.doctor_phone
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorPhone(String doctorPhone) {
        this.doctorPhone = doctorPhone == null ? null : doctorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_info.doctor_photo
     *
     * @return the value of doctor_info.doctor_photo
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getDoctorPhoto() {
        return doctorPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_info.doctor_photo
     *
     * @param doctorPhoto the value for doctor_info.doctor_photo
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDoctorPhoto(String doctorPhoto) {
        this.doctorPhoto = doctorPhoto == null ? null : doctorPhoto.trim();
    }
}