package com.ProClinic.pojo;

import java.util.ArrayList;
import java.util.List;

public class DoctorInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public DoctorInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("doctor_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("doctor_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(Integer value) {
            addCriterion("doctor_id =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(Integer value) {
            addCriterion("doctor_id <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(Integer value) {
            addCriterion("doctor_id >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_id >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(Integer value) {
            addCriterion("doctor_id <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_id <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<Integer> values) {
            addCriterion("doctor_id in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<Integer> values) {
            addCriterion("doctor_id not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(Integer value1, Integer value2) {
            addCriterion("doctor_id between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_id not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIsNull() {
            addCriterion("doctor_name is null");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIsNotNull() {
            addCriterion("doctor_name is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorNameEqualTo(String value) {
            addCriterion("doctor_name =", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotEqualTo(String value) {
            addCriterion("doctor_name <>", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameGreaterThan(String value) {
            addCriterion("doctor_name >", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_name >=", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLessThan(String value) {
            addCriterion("doctor_name <", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLessThanOrEqualTo(String value) {
            addCriterion("doctor_name <=", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLike(String value) {
            addCriterion("doctor_name like", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotLike(String value) {
            addCriterion("doctor_name not like", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIn(List<String> values) {
            addCriterion("doctor_name in", values, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotIn(List<String> values) {
            addCriterion("doctor_name not in", values, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameBetween(String value1, String value2) {
            addCriterion("doctor_name between", value1, value2, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotBetween(String value1, String value2) {
            addCriterion("doctor_name not between", value1, value2, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorSexIsNull() {
            addCriterion("doctor_sex is null");
            return (Criteria) this;
        }

        public Criteria andDoctorSexIsNotNull() {
            addCriterion("doctor_sex is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorSexEqualTo(String value) {
            addCriterion("doctor_sex =", value, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexNotEqualTo(String value) {
            addCriterion("doctor_sex <>", value, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexGreaterThan(String value) {
            addCriterion("doctor_sex >", value, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_sex >=", value, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexLessThan(String value) {
            addCriterion("doctor_sex <", value, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexLessThanOrEqualTo(String value) {
            addCriterion("doctor_sex <=", value, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexLike(String value) {
            addCriterion("doctor_sex like", value, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexNotLike(String value) {
            addCriterion("doctor_sex not like", value, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexIn(List<String> values) {
            addCriterion("doctor_sex in", values, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexNotIn(List<String> values) {
            addCriterion("doctor_sex not in", values, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexBetween(String value1, String value2) {
            addCriterion("doctor_sex between", value1, value2, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorSexNotBetween(String value1, String value2) {
            addCriterion("doctor_sex not between", value1, value2, "doctorSex");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentIsNull() {
            addCriterion("doctor_department is null");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentIsNotNull() {
            addCriterion("doctor_department is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentEqualTo(String value) {
            addCriterion("doctor_department =", value, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentNotEqualTo(String value) {
            addCriterion("doctor_department <>", value, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentGreaterThan(String value) {
            addCriterion("doctor_department >", value, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_department >=", value, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentLessThan(String value) {
            addCriterion("doctor_department <", value, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentLessThanOrEqualTo(String value) {
            addCriterion("doctor_department <=", value, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentLike(String value) {
            addCriterion("doctor_department like", value, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentNotLike(String value) {
            addCriterion("doctor_department not like", value, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentIn(List<String> values) {
            addCriterion("doctor_department in", values, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentNotIn(List<String> values) {
            addCriterion("doctor_department not in", values, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentBetween(String value1, String value2) {
            addCriterion("doctor_department between", value1, value2, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorDepartmentNotBetween(String value1, String value2) {
            addCriterion("doctor_department not between", value1, value2, "doctorDepartment");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusIsNull() {
            addCriterion("doctor_status is null");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusIsNotNull() {
            addCriterion("doctor_status is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusEqualTo(Integer value) {
            addCriterion("doctor_status =", value, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusNotEqualTo(Integer value) {
            addCriterion("doctor_status <>", value, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusGreaterThan(Integer value) {
            addCriterion("doctor_status >", value, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_status >=", value, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusLessThan(Integer value) {
            addCriterion("doctor_status <", value, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_status <=", value, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusIn(List<Integer> values) {
            addCriterion("doctor_status in", values, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusNotIn(List<Integer> values) {
            addCriterion("doctor_status not in", values, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusBetween(Integer value1, Integer value2) {
            addCriterion("doctor_status between", value1, value2, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_status not between", value1, value2, "doctorStatus");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeIsNull() {
            addCriterion("doctor_work_age is null");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeIsNotNull() {
            addCriterion("doctor_work_age is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeEqualTo(Integer value) {
            addCriterion("doctor_work_age =", value, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeNotEqualTo(Integer value) {
            addCriterion("doctor_work_age <>", value, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeGreaterThan(Integer value) {
            addCriterion("doctor_work_age >", value, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_work_age >=", value, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeLessThan(Integer value) {
            addCriterion("doctor_work_age <", value, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_work_age <=", value, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeIn(List<Integer> values) {
            addCriterion("doctor_work_age in", values, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeNotIn(List<Integer> values) {
            addCriterion("doctor_work_age not in", values, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeBetween(Integer value1, Integer value2) {
            addCriterion("doctor_work_age between", value1, value2, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorWorkAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_work_age not between", value1, value2, "doctorWorkAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeIsNull() {
            addCriterion("doctor_age is null");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeIsNotNull() {
            addCriterion("doctor_age is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeEqualTo(Integer value) {
            addCriterion("doctor_age =", value, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeNotEqualTo(Integer value) {
            addCriterion("doctor_age <>", value, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeGreaterThan(Integer value) {
            addCriterion("doctor_age >", value, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_age >=", value, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeLessThan(Integer value) {
            addCriterion("doctor_age <", value, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_age <=", value, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeIn(List<Integer> values) {
            addCriterion("doctor_age in", values, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeNotIn(List<Integer> values) {
            addCriterion("doctor_age not in", values, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeBetween(Integer value1, Integer value2) {
            addCriterion("doctor_age between", value1, value2, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_age not between", value1, value2, "doctorAge");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneIsNull() {
            addCriterion("doctor_phone is null");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneIsNotNull() {
            addCriterion("doctor_phone is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneEqualTo(String value) {
            addCriterion("doctor_phone =", value, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneNotEqualTo(String value) {
            addCriterion("doctor_phone <>", value, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneGreaterThan(String value) {
            addCriterion("doctor_phone >", value, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_phone >=", value, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneLessThan(String value) {
            addCriterion("doctor_phone <", value, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneLessThanOrEqualTo(String value) {
            addCriterion("doctor_phone <=", value, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneLike(String value) {
            addCriterion("doctor_phone like", value, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneNotLike(String value) {
            addCriterion("doctor_phone not like", value, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneIn(List<String> values) {
            addCriterion("doctor_phone in", values, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneNotIn(List<String> values) {
            addCriterion("doctor_phone not in", values, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneBetween(String value1, String value2) {
            addCriterion("doctor_phone between", value1, value2, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhoneNotBetween(String value1, String value2) {
            addCriterion("doctor_phone not between", value1, value2, "doctorPhone");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoIsNull() {
            addCriterion("doctor_photo is null");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoIsNotNull() {
            addCriterion("doctor_photo is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoEqualTo(String value) {
            addCriterion("doctor_photo =", value, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoNotEqualTo(String value) {
            addCriterion("doctor_photo <>", value, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoGreaterThan(String value) {
            addCriterion("doctor_photo >", value, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_photo >=", value, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoLessThan(String value) {
            addCriterion("doctor_photo <", value, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoLessThanOrEqualTo(String value) {
            addCriterion("doctor_photo <=", value, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoLike(String value) {
            addCriterion("doctor_photo like", value, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoNotLike(String value) {
            addCriterion("doctor_photo not like", value, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoIn(List<String> values) {
            addCriterion("doctor_photo in", values, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoNotIn(List<String> values) {
            addCriterion("doctor_photo not in", values, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoBetween(String value1, String value2) {
            addCriterion("doctor_photo between", value1, value2, "doctorPhoto");
            return (Criteria) this;
        }

        public Criteria andDoctorPhotoNotBetween(String value1, String value2) {
            addCriterion("doctor_photo not between", value1, value2, "doctorPhoto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 09 23:05:11 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}