package com.ProClinic.pojo;


import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class PatientInfo {
    @Override
    public String toString() {
        return "PatientInfo{" +
                "patientId=" + patientId +
                ", patientName='" + patientName + '\'' +
                ", patientAge=" + patientAge +
                ", patientPhone='" + patientPhone + '\'' +
                ", patientBirth=" + patientBirth +
                ", patientEmail='" + patientEmail + '\'' +
                ", patientSex='" + patientSex + '\'' +
                ", patientAddress='" + patientAddress + '\'' +
                ", patientCase='" + patientCase + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_name
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer patientAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_phone
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_birth
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd")
    private Date patientBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_email
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String patientEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_sex
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String patientSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_address
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String patientAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_info.patient_case
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String patientCase;

    // 字符串化时间格式
    private String StrPatientBirth;

    public String getStrPatientBirth() {
        return StrPatientBirth;
    }

    public void setStrPatientBirth(String strPatientBirth) {
        StrPatientBirth = strPatientBirth;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_id
     *
     * @return the value of patient_info.patient_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_id
     *
     * @param patientId the value for patient_info.patient_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_name
     *
     * @return the value of patient_info.patient_name
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_name
     *
     * @param patientName the value for patient_info.patient_name
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_age
     *
     * @return the value of patient_info.patient_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getPatientAge() {
        return patientAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_age
     *
     * @param patientAge the value for patient_info.patient_age
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientAge(Integer patientAge) {
        this.patientAge = patientAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_phone
     *
     * @return the value of patient_info.patient_phone
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_phone
     *
     * @param patientPhone the value for patient_info.patient_phone
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_birth
     *
     * @return the value of patient_info.patient_birth
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Date getPatientBirth() {
        return patientBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_birth
     *
     * @param patientBirth the value for patient_info.patient_birth
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientBirth(Date patientBirth) {
        this.patientBirth = patientBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_email
     *
     * @return the value of patient_info.patient_email
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getPatientEmail() {
        return patientEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_email
     *
     * @param patientEmail the value for patient_info.patient_email
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientEmail(String patientEmail) {
        this.patientEmail = patientEmail == null ? null : patientEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_sex
     *
     * @return the value of patient_info.patient_sex
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getPatientSex() {
        return patientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_sex
     *
     * @param patientSex the value for patient_info.patient_sex
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientSex(String patientSex) {
        this.patientSex = patientSex == null ? null : patientSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_address
     *
     * @return the value of patient_info.patient_address
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getPatientAddress() {
        return patientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_address
     *
     * @param patientAddress the value for patient_info.patient_address
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientAddress(String patientAddress) {
        this.patientAddress = patientAddress == null ? null : patientAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_info.patient_case
     *
     * @return the value of patient_info.patient_case
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getPatientCase() {
        return patientCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_info.patient_case
     *
     * @param patientCase the value for patient_info.patient_case
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPatientCase(String patientCase) {
        this.patientCase = patientCase == null ? null : patientCase.trim();
    }
}