package com.ProClinic.pojo;

public class UserAdmin {
    @Override
    public String toString() {
        return "UserAdmin{" +
                "username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", email='" + email + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.username
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.password
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.email
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.username
     *
     * @return the value of user_admin.username
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.username
     *
     * @param username the value for user_admin.username
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.password
     *
     * @return the value of user_admin.password
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.password
     *
     * @param password the value for user_admin.password
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.email
     *
     * @return the value of user_admin.email
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.email
     *
     * @param email the value for user_admin.email
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}