package com.ProClinic.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class WaitingInfo {
    @Override
    public String toString() {
        return "WaitingInfo{" +
                "waitingId=" + waitingId +
                ", waitingPatientId=" + waitingPatientId +
                ", waitingDoctorId=" + waitingDoctorId +
                ", waitingStatus=" + waitingStatus +
                ", waitingUpdate=" + waitingUpdate +
                ", waitingCost=" + waitingCost +
                ", waitingDiscount=" + waitingDiscount +
                ", waitingDate=" + waitingDate +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waiting_info.waiting_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer waitingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waiting_info.waiting_patient_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer waitingPatientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waiting_info.waiting_doctor_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer waitingDoctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waiting_info.waiting_status
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Integer waitingStatus = 2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waiting_info.waiting_update
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date waitingUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waiting_info.waiting_cost
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private BigDecimal waitingCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waiting_info.waiting_discount
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    private Float waitingDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waiting_info.waiting_date
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd")
    private Date waitingDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waiting_info.waiting_id
     *
     * @return the value of waiting_info.waiting_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getWaitingId() {
        return waitingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waiting_info.waiting_id
     *
     * @param waitingId the value for waiting_info.waiting_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setWaitingId(Integer waitingId) {
        this.waitingId = waitingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waiting_info.waiting_patient_id
     *
     * @return the value of waiting_info.waiting_patient_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getWaitingPatientId() {
        return waitingPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waiting_info.waiting_patient_id
     *
     * @param waitingPatientId the value for waiting_info.waiting_patient_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setWaitingPatientId(Integer waitingPatientId) {
        this.waitingPatientId = waitingPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waiting_info.waiting_doctor_id
     *
     * @return the value of waiting_info.waiting_doctor_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getWaitingDoctorId() {
        return waitingDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waiting_info.waiting_doctor_id
     *
     * @param waitingDoctorId the value for waiting_info.waiting_doctor_id
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setWaitingDoctorId(Integer waitingDoctorId) {
        this.waitingDoctorId = waitingDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waiting_info.waiting_status
     *
     * @return the value of waiting_info.waiting_status
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Integer getWaitingStatus() {
        return waitingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waiting_info.waiting_status
     *
     * @param waitingStatus the value for waiting_info.waiting_status
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setWaitingStatus(Integer waitingStatus) {
        this.waitingStatus = waitingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waiting_info.waiting_update
     *
     * @return the value of waiting_info.waiting_update
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Date getWaitingUpdate() {
        return waitingUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waiting_info.waiting_update
     *
     * @param waitingUpdate the value for waiting_info.waiting_update
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setWaitingUpdate(Date waitingUpdate) {
        this.waitingUpdate = waitingUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waiting_info.waiting_cost
     *
     * @return the value of waiting_info.waiting_cost
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public BigDecimal getWaitingCost() {
        return waitingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waiting_info.waiting_cost
     *
     * @param waitingCost the value for waiting_info.waiting_cost
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setWaitingCost(BigDecimal waitingCost) {
        this.waitingCost = waitingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waiting_info.waiting_discount
     *
     * @return the value of waiting_info.waiting_discount
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Float getWaitingDiscount() {
        return waitingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waiting_info.waiting_discount
     *
     * @param waitingDiscount the value for waiting_info.waiting_discount
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setWaitingDiscount(Float waitingDiscount) {
        this.waitingDiscount = waitingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waiting_info.waiting_date
     *
     * @return the value of waiting_info.waiting_date
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public Date getWaitingDate() {
        return waitingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waiting_info.waiting_date
     *
     * @param waitingDate the value for waiting_info.waiting_date
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    public void setWaitingDate(Date waitingDate) {
        this.waitingDate = waitingDate;
    }
}