package com.ProClinic.mapping;

import com.ProClinic.pojo.DoctorInfo;
import com.ProClinic.pojo.DoctorInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DoctorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int countByExample(DoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int deleteByExample(DoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int deleteByPrimaryKey(Integer doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int insert(DoctorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int insertSelective(DoctorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    List<DoctorInfo> selectByExample(DoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    DoctorInfo selectByPrimaryKey(Integer doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") DoctorInfo record, @Param("example") DoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByExample(@Param("record") DoctorInfo record, @Param("example") DoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByPrimaryKeySelective(DoctorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByPrimaryKey(DoctorInfo record);
}