package com.ProClinic.mapping;

import com.ProClinic.pojo.UserAdmin;
import com.ProClinic.pojo.UserAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int countByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int deleteByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int insert(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int insertSelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    List<UserAdmin> selectByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    UserAdmin selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByExample(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByPrimaryKeySelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByPrimaryKey(UserAdmin record);
}