package com.ProClinic.mapping;

import com.ProClinic.pojo.WaitingInfo;
import com.ProClinic.pojo.WaitingInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WaitingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int countByExample(WaitingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int deleteByExample(WaitingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int deleteByPrimaryKey(Integer waitingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int insert(WaitingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int insertSelective(WaitingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    List<WaitingInfo> selectByExample(WaitingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    WaitingInfo selectByPrimaryKey(Integer waitingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") WaitingInfo record, @Param("example") WaitingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByExample(@Param("record") WaitingInfo record, @Param("example") WaitingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByPrimaryKeySelective(WaitingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waiting_info
     *
     * @mbggenerated Wed Nov 09 23:05:11 CST 2022
     */
    int updateByPrimaryKey(WaitingInfo record);
}